### ISSUE TITLE
[Suggestion] Emoji picker compatibility 

### ISSUE THREAD

**Issue by tienesphus** [Yentis/betterdiscord-emotereplacer#13]
Would be cool if you can make the plugin compatible with both autocomplete and emoji picker.

**Comment by Yentis** [comment]
Possible duplicate of https://github.com/Yentis/betterdiscord-emotereplacer/issues/4 ?

**Comment by tienesphus** [comment]
Yeah my bad. Skimmed through the issue list but I missed it :).
