### ISSUE TITLE
Modifiers dont work when used on an emote within its original server

### ISSUE THREAD

**Issue by tienesphus** [Yentis/betterdiscord-emotereplacer#14]
Assuming I am in server A which has emote B. I can not use **_B.flip_** within server A. Using **_B.flip_** in any other servers works fine.

**Comment by Yentis** [comment]
This is because the plugin only applies itself to emotes that aren't currently available (eg: emotes from other servers).
The same issue will occur if you have nitro.

A possible solution could be to look for any normal emotes that are followed by some modifier.

**Comment by Yentis** [comment]
Implemented in 1.9.2
