### ISSUE TITLE
Hide Gift Feature not working

### ISSUE THREAD

**Issue by joesphan** [Yentis/betterdiscord-emotereplacer#15]
Hi! I just installed betterdiscord to remove the minimum window size limit, however I found that the hide gift feature is not working.  Keep up the good work, devs!

Stable 84785 (fe5e237)
BetterDiscord 1.1.0
Host 1.0.9001
Windows 10 64-Bit (10.0.19042)

**Comment by Yentis** [comment]
Wrong repo https://github.com/rauenzi/BetterDiscordApp

**Comment by joesphan** [comment]
sorry lol
