### ISSUE TITLE
[Suggestion] Modifiers on all emotes

### ISSUE THREAD

**Issue by cityrobo** [Yentis/betterdiscord-emotereplacer#16]
I love the emotes and the modifiers, but I currently find it bothersome to copy the emote's picture and make it a custom emote only to be able to apply all the cool modifiers on them.

I would love it if I was able to do `:emote_from_any_server.modifier` instead of only `;customemote.modifier`.

I don't know if it's possible, but it would definitely make quick reactions with modifiers a lot... well... quicker :D 
cause you wouldn't need to copy the emote into your custom emotes first to apply the modifiers.

**Comment by Yentis** [comment]
This is already possible, remove the space after a normal emote and put your modifiers like you would with custom emotes.
https://streamable.com/t8ffhe
