### ISSUE TITLE
forbidden emoji error 

### ISSUE THREAD

**Issue by ChrisFarmer-dev** [Yentis/betterdiscord-emotereplacer#19]
### Error Info:
There are random emotes/emojis that do not work and throw a forbidden error. I did get some other errors other than the `forbidden error` but I got them only once. 

### Date of Error
I have gotten it multiple times, I even got it today. 

> ### Examples:

### 1. 
![pepeAhh](https://i.imgur.com/RCcoEQX.gif)

### 2. 
![twerk](https://i.imgur.com/rXpUTvj.gif)

### 3. 
![pepeHigh](https://i.imgur.com/fszq2zd.gif)

**Comment by Yentis** [comment]
Please post the links used for these emojis

**Comment by ChrisFarmer-dev** [comment]
yea sure 
https://cdn.discordapp.com/attachments/770181725006462988/848812891481178143/amogus.gif
https://cdn.discordapp.com/attachments/770181725006462988/848812833205387284/pepetwerk.gif
https://cdn.discordapp.com/attachments/770181725006462988/849218276332797952/pepeAhh.gif
https://cdn.discordapp.com/attachments/854290624155746314/854334644622983178/pepeHigh.png

**Comment by Yentis** [comment]
The pepeHigh link is dead, the others seem to be working fine for me. Ensure you're on at least 1.9.3 or upload the emotes to a site like imgur.

Using an emoji link instead of an attachment will also give better results, eg: https://cdn.discordapp.com/emojis/<emoteid>.png
which you can get by right clicking an emoji and pressing copy link

**Comment by ChrisFarmer-dev** [comment]
Oh, interesting, Yea I will use Imgur instead. Just for info, I think these emotes stopped working after like previous 1.9.3 update Idk if it's because of the update or something else but I started getting this error.  
![working](https://i.imgur.com/r1E1Qtt.gif)
Also thank you for making this plugin🙏
