### ISSUE TITLE
text after emoji with modifier doesn't appear.

### ISSUE THREAD

**Issue by ChrisFarmer-dev** [Yentis/betterdiscord-emotereplacer#20]
### Error Info:
If I added text after an emoji with a modifier it doesn't appear or send it. 

### Date of Error
I have gotten it multiple times, I even got it today.

> ### Examples
### 1.
![emoji with modifier](https://i.imgur.com/kwvQaet.gif)

I don't know if this will help you but I feel extra info might help. Text after emojis without modifers do appear or send. 
![emoji without modifier](https://i.imgur.com/KqykJgT.gif)

**Comment by Yentis** [comment]
Fixed in 1.9.4

**Comment by ChrisFarmer-dev** [comment]
Thank you very much for making a great plugin boss 🙏
