### ISSUE TITLE
Can't say numbers

### ISSUE THREAD

**Issue by PereiraBackup** [Yentis/betterdiscord-emotereplacer#22]
You can't say some numbers because of the invalid url

![image](https://user-images.githubusercontent.com/86084363/122482600-c88c9f80-cfc8-11eb-8e03-ba58fb4e8d22.png)
![image](https://user-images.githubusercontent.com/86084363/122482615-cd515380-cfc8-11eb-9d79-55639e847492.png)

**Comment by Yentis** [comment]
Needs more info

**Comment by Yentis** [comment]
Fixed in 1.9.6
