### ISSUE TITLE
.speed Modifiers throws an error

### ISSUE THREAD

**Issue by ChrisFarmer-dev** [Yentis/betterdiscord-emotereplacer#23]
### Error Info:
speed modifier throws an error. it doesnt depend upon the emote or the speed (fast, faster, hyper) it just keeps giving the same error.

### Date of Error
I have gotten it multiple times, I even got it today.

> ### Example
![mod](https://i.imgur.com/U3SOtMb.gif)

**Comment by Yentis** [comment]
.speed-<speed> - For gifs, change delay between frames in hundredths of a second.
Meaning it should be a number, the lower the faster
