### ISSUE TITLE
[Suggestion] Press enter to send the emote instantly

### ISSUE THREAD

**Issue by sordinary** [Yentis/betterdiscord-emotereplacer#24]
First of all, very nice plugin. But it's a bit counter intuitive. Like having to click on the emote before pressing enter. 

https://i.imgur.com/wzMNlYe.gif - instantly pressing enter

https://i.imgur.com/Fswasi5.gif - clicking the emote first before pressing enter

https://i.imgur.com/tmnZrg3.gif - normal discord emote pressing enter instantly

**Comment by sordinary** [comment]
Oh yeah, it would be nice if you can turn the case sensitive off in the settings.

Thanks!

**Comment by Yentis** [comment]
Note that you can use tab to autocomplete the emotes as well

**Comment by Yentis** [comment]
Done in 1.9.6
