### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sordinary** [Yentis/betterdiscord-emotereplacer#25]
Hey, I tried re-downloading the plugin from this repository, no luck.

https://i.imgur.com/NXYnTCk.png

**Comment by Alicyl** [comment]
I'm having the same issue, and EmoteReplacer disappeared from the Plugin Repository as well as my list of plugins; I have no idea what to do to fix it, so... I guess I'll wait for the next update.

**Comment by Yentis** [comment]
Fixed in 1.9.8
