### ISSUE TITLE
Gifs not sending, stuck on "Processing gif" until gifsicle is modified

### ISSUE THREAD

**Issue by MasterIO02** [Yentis/betterdiscord-emotereplacer#26]
Hi, so I'm facing this issue since about 1-2 months, I can't seem to send gifs anymore with emotereplacer.
Emotereplacer sends the "Processing gif..." toast notification and then nothing happens, unless you wait for ~5 minutes or you rename/move/delete the gifsicle executable in the plugins folder of betterdiscord.
After that, no gifs will be processed correctly as gifsicle would not be present, until you restore it back in the plugins folder, and then when you try again to send a gif it gets stuck on processing gif.
I compiled the latest gifsicle version and the problem still occurs.
Sending non-gif emotes work as expected.

I am on Linux, KDE neon (ubuntu based) if that matters.

**Comment by Yentis** [comment]
Fixed in 1.9.9

**Comment by MasterIO02** [comment]
Thank you!
