### ISSUE TITLE
Better splitting of messages and emotes? 

### ISSUE THREAD

**Issue by ImmortalZypther** [Yentis/betterdiscord-emotereplacer#28]
Currently, all emotes send after the message, but could you make it so emotes placed before the message send before the message? 

This plugin has an implementation of it in its "split" version, but yours could be better if it were also compatible with images. 

https://github.com/An00nymushun/DiscordFreeEmojis

In my opinion, images should be sent after the message that you type with it along with any emotes, but having a toggle for before or after would be fine too.

Just to be clear, here would be how various messages are formatted if you were to implement this:

1. ":emote: Words words words" -> Emote gets sent first, then the words are sent below it.
2. "Words words words :emote:" -> Words are sent first, then the emote gets sent below it. This is the current implementation. 
3. "Words words :emote: words" -> The message gets split into "Words words", followed by the emote, followed by "words"
4. "Words words :emote: [image.png]" -> The message will be formatted according to the above 3 examples, which is then followed by the image upload.

**Comment by Yentis** [comment]
This is only possible by sending multiple messages, as this plugin works by uploading images instead of emotes. All images that are uploaded go under the text content and I don't really want to send multiple messages for only a single input as this might fall under self-botting.
