### ISSUE TITLE
[FEATURE] Modifier Option Tip / Autocomplete Modifier Options 

### ISSUE THREAD

**Issue by ChrisFarmer-dev** [Yentis/betterdiscord-emotereplacer#33]
## [FEATURE] Modifier Option Tip / Autocomplete Modifier Options 

Hey Yentis, thank you for creating such a great plugin. It would be great if there was an autocomplete modifier options (like the modifiers) or something like this would be awesome as well
![image](https://user-images.githubusercontent.com/71568799/134781382-71816cb5-53d5-466a-84ba-d8cf33fe3941.png)
This feature would be great for the plugin because whenever I use a modifier, I keep forgetting what are the available options and either I type the wrong a modifier option, or I must refer to the GitHub page which takes time to search and stuff. 
This would be a GREAT feature. Thank you so much 🙏

**Comment by Yentis** [comment]
Done in 1.11.0
