### ISSUE TITLE
Emote take long time to send

### ISSUE THREAD

**Issue by OshidaBCF** [Yentis/betterdiscord-emotereplacer#40]
Sometime when i try to send an emote, nothing happen for a long time (a minute or so) then it get sent.

it's kinda annoying and sometime it send when i'm writting another message that's either a "reply" or contain an image or something else, so the message lose all it's meaning.

I have no idea why it happen, i can send big files really fast like normal.

**Comment by Yentis** [comment]
It should only take a long time to send if you're using a lot of modifiers or using a very large source image, if you have an image you can reproduce it with let me know.

**Comment by OshidaBCF** [comment]
https://user-images.githubusercontent.com/61458287/206873734-fda84554-9c31-4651-aa5e-bd8077dc6498.mp4

hello, i completely forgot about better discord so i just reinstalled it

The bug still happen, but randomly, just after installing the pluging i tested it and it send the emote with 10-20 seconds of delay, then after i booted up OBS to record it, it refused to send anything, and sometime if i send one, then another it would send both instantly after i send the second one.

So i don't know.

**Comment by Yentis** [comment]
Can you tell me your system specs including the OS you use?

**Comment by OshidaBCF** [comment]
GTX 1080
Ryzen 7 1700
32 gig of ram

Windows 10

**Comment by Yentis** [comment]
If this still happens, try doing a full restart of Discord. I had a similar issue and nothing I changed helped except restarting the entire Discord client.

**Comment by OshidaBCF** [comment]
i have rebooted my PC a few times since that day, for now it didn't happened again.

**Comment by KotMonsoon** [comment]
have same issue, it refuses to send any emote and even any message that was with emote and if i try to send any message in response to someones message after "not sending" emote it will break and my every message after that one will be response to same message until i reboot discord 

https://user-images.githubusercontent.com/109630293/217407161-46bbf6ab-fd48-40d3-86ab-5dd0283c8ccf.mp4

**Comment by OshidaBCF** [comment]
Same here, i can't record it because it's very random

**Comment by Yentis** [comment]
Assumed fixed in 2.0.0
Create a new issue if you still have problems
