### ISSUE TITLE
Plugin doesn't work since the big discord update

### ISSUE THREAD

**Issue by nefariouslegion** [Yentis/betterdiscord-emotereplacer#42]
BetterDiscord says the plugin can't be compiled 
![image](https://user-images.githubusercontent.com/89366675/192842894-3763e0fe-253b-4528-a258-37431b3497cb.png)

**Comment by Yentis** [comment]
Plugin compiles with the current source (no plugin.js yet) but there are still many Discord modules patched that I don't yet know how to fix.

**Comment by JohnjiRomanji** [comment]
> Plugin compiles with the current source 

What do you mean by current source? Is there a way to reinstall so it works? 
Sorry if these questions are very simple...

**Comment by Yentis** [comment]
No, the plugin doesn't work but I have fixed it not compiling at all. Source means the source code, since the plugin isn't fixed I haven't built it into a plugin.js file yet that you could use.

**Comment by JohnjiRomanji** [comment]
Oh I see, thank you!

**Comment by OshidaBCF** [comment]
So it's "fixed" but not "public" yet ?

**Comment by Yentis** [comment]
Like I already said, the plugin doesn't work. Why would I fix it but not release it?

**Comment by OshidaBCF** [comment]
Sorry i missunderstood

**Comment by Yentis** [comment]
Fixed in 1.12.2. Ensure you're using BD 1.8.0
