### ISSUE TITLE
Is it still broken?

### ISSUE THREAD

**Issue by Chhezik** [Yentis/betterdiscord-emotereplacer#44]
After the discord's update, this plugin still seems to be broken. i would like to know if its being worked on since i recently discovered this amazing plugin and i would love to see it working.

**Comment by Yentis** [comment]
Duplicate of https://github.com/Yentis/betterdiscord-emotereplacer/issues/42
The plugin is fixed in version 1.12.2

BD has still not approved my update so it won't show in the auto-updater.
