### ISSUE TITLE
It seems to be broken again

### ISSUE THREAD

**Issue by OshidaBCF** [Yentis/betterdiscord-emotereplacer#46]
The preview in the text zone still works, but when i press enter the message get "sent" but not really, it just clear out the text zone

**Comment by Shadowdish** [comment]
same

**Comment by Andore97** [comment]
yep, in your own chat its visible but when you press Enter it happend nothing

**Comment by OshidaBCF** [comment]
Indeed, like if it was "forgetting" to send the message

**Comment by Yentis** [comment]
Fixed in 1.12.3

**Comment by Visne** [comment]
Seems to still be broken when replying to someone:
![image](https://user-images.githubusercontent.com/39844191/211391773-6ce3fc27-7b80-40b1-b76b-8372b729bdbb.png)

If I add some text to the reply it only replies with text and the emoji disappears again.

**Comment by Shadowdish** [comment]
Kinda happened to me but it was only for a certain emoji

**Comment by Shadowdish** [comment]
nvm had the same exact emoji send and it sent normally now

**Comment by Shadowdish** [comment]
ok yeah it's whenever you reply to text message that it doesn't want to appear

**Comment by Yentis** [comment]
Should work now with 1.12.4
Let me know if you have any further issues.

**Comment by OshidaBCF** [comment]
Works for me

Thanks
