### ISSUE TITLE
[Suggestion] Hide emojis I can't use for reactions

### ISSUE THREAD

**Issue by Visne** [Yentis/betterdiscord-emotereplacer#49]
While this plugin makes it possible to post emojis everywhere, it doesn't make it possible to use any emoji to react. The emoji picker will still show all emojis, however (at least, it won't grey them out). This is especially frustrating when multiple servers use the same emoji image, because then you manually have to check which one is the correct one to use.

**Comment by Yentis** [comment]
Done in 1.13.0

**Comment by Visne** [comment]
Works perfectly, thanks for maintaining this plugin.
