### ISSUE TITLE
Certain emotes not uploading

### ISSUE THREAD

**Issue by programmer2514** [Yentis/betterdiscord-emotereplacer#5]
I found this plugin the other day, and I really like it. I just have one issue:
Most emotes seem to work fine, but with some emotes (E.G. yentStitchCry), it just says `Processing gif...` and then the message fails to send.

EDIT: It appears this happens sporadically - It's not always the same emoji/modifier combination. It seems random

**Comment by Yentis** [comment]
I've encountered this before, it can happen with any emote that ends up as a gif. I'll look into it some more.
