### ISSUE TITLE
Emote are sent in "main" channel if thread isn't "fully" open

### ISSUE THREAD

**Issue by OshidaBCF** [Yentis/betterdiscord-emotereplacer#53]
![image](https://user-images.githubusercontent.com/61458287/221248813-339af6a4-1b03-457f-95a2-b95301e09366.png)

You can see on the picture that i have the thread textbox selected.
I tried to send an emote but it instead sent it in the "main" channel, which i'm not allowed to anyway.

The emote should send in the "selected" channel.

**Comment by Yentis** [comment]
Fixed in 1.13.1
