### ISSUE TITLE
Plugin broken: this.modulesService.cloudUploader.n is not a constructor

### ISSUE THREAD

**Issue by LockBlock-dev** [Yentis/betterdiscord-emotereplacer#55]
I am getting the following error since a few days when sending a message with an emote:
```
EmoteReplacer Error in onDeletePendingReply TypeError: this.modulesService.cloudUploader.n is not a constructor
    at SendMessageService.uploadFile (EmoteReplacer.plugin.js:24252)
    at SendMessageService.fetchBlobAndUpload (EmoteReplacer.plugin.js:24185)
```
**Plugin version:** 1.13.0 (latest)
**Better Discord version:** 1.9.0 (latest)
**OS:** Arch Linux
**OpenAsar:** 40b27dd (latest Nightly)

**Comment by Yentis** [comment]
See https://github.com/Yentis/betterdiscord-emotereplacer/issues/54
