### ISSUE TITLE
Seemingly broken on newest discord update.

### ISSUE THREAD

**Issue by tjhexf** [Yentis/betterdiscord-emotereplacer#57]
![image](https://user-images.githubusercontent.com/97811916/227721561-4430a8ac-1b52-459c-9fc4-4b5fc410dfd0.png)

**Comment by Yentis** [comment]
This is an issue with BD https://github.com/BetterDiscord/BetterDiscord/issues/1583

**Comment by tjhexf** [comment]
Ah, understandable, let's hope they fix it soon

**Comment by Yentis** [comment]
Temp fixed version until BD fixes the issue:
https://paste2.org/z8nHId4I

**Comment by Andore97** [comment]
> 

not working, it says "meta not found" and crashing my discord if im trying to click on info for the error

**Comment by Yentis** [comment]
There's no issue with the fixed version, are you sure you saved it correctly?

**Comment by Andore97** [comment]
> 

![grafik](https://user-images.githubusercontent.com/64412622/228666192-5e19aead-6f11-439b-88dc-e5558c70a813.png)

**Comment by Miniontoby** [comment]
> Temp fixed version until BD fixes the issue: https://github.com/Yentis/betterdiscord-emotereplacer/blob/8c46b80dc4e81b2ec2886dc59e8c54f691a65ca2/EmoteReplacer.plugin.js

for me it works

**Comment by OshidaBCF** [comment]
I tryied to update the plugin manually, but i can't access the plugins settings now

**Comment by Yentis** [comment]
If you encounter any strange issues please first try to restart discord fully

**Comment by Andore97** [comment]
@Yentis 
![grafik](https://user-images.githubusercontent.com/64412622/230346341-01f7b495-1ed3-46d6-bcd8-3bceaf161587.png)

**Comment by OshidaBCF** [comment]
Even after a restart i cannot open the plugin settings, yet i do not get any error

**Comment by Yentis** [comment]
Make sure ZeresPluginLibrary is on version 2.0.14 and double check that you updated my plugin correctly (check if other things work as they should)

**Comment by Andore97** [comment]
ZeresPluginLibrary is on 2.0.14, i even reinstalled discord+betterdiscord

still this meta error

**Comment by Yentis** [comment]
https://raw.githubusercontent.com/Yentis/betterdiscord-emotereplacer/8c46b80dc4e81b2ec2886dc59e8c54f691a65ca2/EmoteReplacer.plugin.js

Open this, right click on the page and press save as (or press ctrl + s).
Then save it in your plugins folder and restart discord.

**Comment by Andore97** [comment]
Oh now its working, last times i rightclick it and saved... but now its a new problem.. it takes like 25 seconds to use any Emote with emotereplacer

**Comment by OshidaBCF** [comment]
Well, it working now, even tho i updated the plugin an hour ago

**Comment by Yentis** [comment]
Fixed in 2.0.0
