### ISSUE TITLE
Unable to select emote from the list.

### ISSUE THREAD

**Issue by emmemmy** [Yentis/betterdiscord-emotereplacer#59]
As the title says, I am unable to select an emote from the list after typing ;(searchterm). I cannot click to select an emote, or use enter to select and emote. This happened with the "fixed" version (from being broken by betterdiscord), and the "unfixed" normal version. I've tried it with all other plugins but emotereplacer and the library disabled, but I still can't get it to work.

**Comment by Yentis** [comment]
Assumed fixed in 2.0.0
Create a new issue if you still have problems
