### ISSUE TITLE
Could not open settings.

### ISSUE THREAD

**Issue by cityrobo** [Yentis/betterdiscord-emotereplacer#61]
Fresh Update of BetterDiscord and only having ZeresPluginLibrary 2.0.14 and EmoteReplacer 1.13.1 installed causes a red warning to appear when I try to change the settings of EmoteReplacer in the BetterDiscord plugins menu, aka pressing the settings cogwheel.

It's been this way for me for a long while now, long before updating BetterDiscord.

EmoteReplacer itself seems to be broken for me in general too, but that might be update related? I am now using BetterDiscord 1.9.1 .

![image](https://user-images.githubusercontent.com/84413175/230638219-cfdef881-2f6f-4940-bf92-f04503afc3e6.png)

**Comment by Yentis** [comment]
Assumed fixed in 2.0.0
Create a new issue if you still have problems
