### ISSUE TITLE
Sticker support

### ISSUE THREAD

**Issue by Visne** [Yentis/betterdiscord-emotereplacer#73]
It seems to me like stickers could be supported in a very similar way that emoji's are currently supported.

**Comment by Yentis** [comment]
Added in 2.1.0

**Comment by Visne** [comment]
Thank you! Just in case you're not aware of it, the default Nitro stickers don't work (the ones you get if you go to the stickers tab and the scroll down in the server list to the Nitro icon). I personally don't really care about those, though.

**Comment by Yentis** [comment]
Yeah, that's intentional. Discord's official stickers are copyrighted so letting my plugin send those is asking for toruble.

**Comment by Visne** [comment]
Makes sense, thanks again!
