### ISSUE TITLE
[Suggestion] Implementing the plugin to Vencord

### ISSUE THREAD

**Issue by LightShaft** [Yentis/betterdiscord-emotereplacer#74]
I've switched to Vencord very recently. Performance-wise it's working so much better. There is FakeNitro that is working nicely but I prefer emotereplacer because I think it works better when it comes to emojis. I just can't install the plugin myself so ... yeah, that's why I'm posting this.

https://github.com/Vendicated/Vencord/blob/main/docs/2_PLUGINS.md
I've stumbled onto this but I don't understand any of it.
I don't think there was a post mentionning Vencord before, hence why I'm suggesting it. Would be very nice.
Cheers

**Comment by Yentis** [comment]
Sorry, I don't really want to maintain the plugin for multiple discord clients. I would have to constantly switch between Vencord and BD when developing.
