### ISSUE TITLE
[Bug] Plugin isn't working until I send first available emoji

### ISSUE THREAD

**Issue by KulaGGin** [Yentis/betterdiscord-emotereplacer#77]
Until I send first emoji that's available to me, I can't sent emojis that are only available with nitro. Plugin only starts to work after I send an emoji that's available to me. Here's the video with demonstration:

https://github.com/Yentis/betterdiscord-emotereplacer/assets/16989713/cf37eb40-9459-4d61-aaf9-09ae9382ebab

**Comment by Yentis** [comment]
Should be fixed in 2.1.2
