### ISSUE TITLE
[Bug] Prefix and custom emotes doesn't work

### ISSUE THREAD

**Issue by Arcrous** [Yentis/betterdiscord-emotereplacer#81]
Plugin prefix doesn't open the custom emote list (default or added).

Grabbing normal emotes works fine however

 - OS: Win 11
 - Version 2.1.1 + 2.0.18

https://github.com/Yentis/betterdiscord-emotereplacer/assets/128874159/81d549ae-e3b5-4bc2-960c-41d217917d72

**Comment by Yentis** [comment]
Fixed in 2.1.2
