### ISSUE TITLE
[Bug] Plugin no longer work after recent discord and betterdiscord update

### ISSUE THREAD

**Issue by OshidaBCF** [Yentis/betterdiscord-emotereplacer#82]
Plugin no longer work after recent discord and betterdiscord update

![image](https://github.com/Yentis/betterdiscord-emotereplacer/assets/61458287/6169a65b-6a16-410b-b760-7030884adbba)

 - OS: Windows 10
 - Version 2.1.2

**Comment by Yentis** [comment]
Fixed in 2.1.3

**Comment by OshidaBCF** [comment]
sweet
