### ISSUE TITLE
[Suggestion] Disable or improve stickers

### ISSUE THREAD

**Issue by 2l47** [Yentis/betterdiscord-emotereplacer#83]
**Is your feature request related to a problem? Please describe.**
I use a different plugin, [FreeStickers](https://github.com/riolubruh/DiscordFreeStickers), to send [links](https://media.discordapp.net/stickers/949905645866459196.png?size=160) to stickers. EmoteReplacer currently sends a blurry rescaled image. With both plugins enabled, the sticker is sent as a link and as a blurry image.
![image](https://github.com/Yentis/betterdiscord-emotereplacer/assets/80786286/b92d1382-9566-474f-a794-d6db7a6755a1)

**Describe the solution you'd like**
Provide an option to disable the sticker sending functionality and/or improve the resolution of the sticker image sent. The sticker used in this example appears to have a max resolution of 128x72 px. It might be necessary to check the size of a sticker before attempting to rescale it.

**Comment by Yentis** [comment]
Go into settings and select "Scale down largest side" under "Resize method"

**Comment by 2l47** [comment]
That's much better, but it's still upscaling the image resulting in some loss of quality.

**Comment by Yentis** [comment]
Stickers will scale using url where possible in 2.1.5, if this doesn't return a 160px image then scaling will still need to be done by the plugin to match the standard 160px size for stickers.
