### ISSUE TITLE
[Bug] Plugin works but emotes in "emote menu" are locked

### ISSUE THREAD

**Issue by OshidaBCF** [Yentis/betterdiscord-emotereplacer#85]
**Describe the bug**
The plugins works normally but all emotes appears "locked" in the emote menu, you can still click on them and it works tho, so this is purely visual i assume

**To Reproduce**
1. Open Emote Menu (Ctrl+E)
2. See error

**Expected behavior**
Before all the "ads" part that tells you emotes are locked and you need to buy nitro was hidden, now it's back

**Screenshots**
![image](https://github.com/user-attachments/assets/2a0abb5a-8718-47ee-8a80-7646ee604987)

 - OS: Windows 10
 - Version: 2.1.7

**Comment by Yentis** [comment]
Fixed in 2.2.0
