### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by XM0ni** [Yentis/betterdiscord-emotereplacer#87]
**Describe the bug**
Newest update, 2.2.0, breaks the plugin and it no longer works

**To Reproduce**
1. Update to 2.2.0 or download 2.2.0
2. Tried to send an emoji
3. Doesn't work anymore

**Expected behavior**
The emojis are supposed to embed, but instead it just sends the text of the emoji

**Screenshots**
![image](https://github.com/user-attachments/assets/4e54f4b9-8465-478e-83a0-05a6437b535e)

 - OS: [e.g. Windows 10]
 - Version [e.g. 2.1.1]

**Additional context**
none of the emojis are appearing when you type ":" except default ones

**Comment by Yentis** [comment]
Still works for me, make sure you have the latest BD and restart discord.

**Comment by XM0ni** [comment]
Oh I didn't realize that discord wasn't updated, Sorry! That fixed it-
